### ISSUE TITLE
Backlog Issues - Rodrigo

### ISSUE THREAD

**Issue by moss2510** [rjdsilv/COMP305_FinalProject#7]
Please Update the pending task from your end (Weekly).
Please update the ticket and assign the ticket back to me before any push to master.

**Comment by rjdsilv** [comment]
Introduced a lot of new code to support battles. Battles not implemented yet, but most of the support code needed for it was included. The code introduced some bugs that were fixed. Please, test the code and if everything is ok, approve my pull request to master.

**Comment by moss2510** [comment]
Backlog - Implementation of battles.
Reid and Jalpen's code to be pushed to master branch and test the game.
