### ISSUE TITLE
Create the temple battle scene.

### ISSUE THREAD

**Issue by rjdsilv** [rjdsilv/COMP305_FinalProject#97]

**Comment by moss2510** [comment]
The portions that player had to collect in temple can be seen in overlay of the battle scene in temple. 
Portions appear in static position in which they were before the battle starts.

**Comment by moss2510** [comment]
Tested fine now. 
Will keep this ticket open till Beta build.
Do not Close Ticket.

**Comment by moss2510** [comment]
Will open a new ticket if the issue reoccurs.
Closing now.
